// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.common.msg.bean;

public final class BaseBean {
  private BaseBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.common.msg.bean.BaseBean.cgPlayerCheckLogin);
    registry.add(com.common.msg.bean.BaseBean.gcPlayerCheckLogin);
    registry.add(com.common.msg.bean.BaseBean.missionInfo);
    registry.add(com.common.msg.bean.BaseBean.missionReward);
  }
  public interface BaseMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<BaseMessage> {

    // required .bean.BaseMessage.Type type = 1;
    /**
     * <code>required .bean.BaseMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .bean.BaseMessage.Type type = 1;</code>
     */
    com.common.msg.bean.BaseBean.BaseMessage.Type getType();
  }
  /**
   * Protobuf type {@code bean.BaseMessage}
   */
  public static final class BaseMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        BaseMessage> implements BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.common.msg.bean.BaseBean.BaseMessage, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseMessage defaultInstance;
    public static BaseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.common.msg.bean.BaseBean.BaseMessage.Type value = com.common.msg.bean.BaseBean.BaseMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.msg.bean.BaseBean.internal_static_bean_BaseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.msg.bean.BaseBean.internal_static_bean_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.msg.bean.BaseBean.BaseMessage.class, com.common.msg.bean.BaseBean.BaseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code bean.BaseMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CGPLAYERCHECKLOGIN = 1;</code>
       */
      CGPLAYERCHECKLOGIN(0, 1),
      /**
       * <code>GCPLAYERCHECKLOGIN = 2;</code>
       */
      GCPLAYERCHECKLOGIN(1, 2),
      /**
       * <code>MISSIONINFO = 3;</code>
       */
      MISSIONINFO(2, 3),
      /**
       * <code>MISSIONREWARD = 4;</code>
       */
      MISSIONREWARD(3, 4),
      ;

      /**
       * <code>CGPLAYERCHECKLOGIN = 1;</code>
       */
      public static final int CGPLAYERCHECKLOGIN_VALUE = 1;
      /**
       * <code>GCPLAYERCHECKLOGIN = 2;</code>
       */
      public static final int GCPLAYERCHECKLOGIN_VALUE = 2;
      /**
       * <code>MISSIONINFO = 3;</code>
       */
      public static final int MISSIONINFO_VALUE = 3;
      /**
       * <code>MISSIONREWARD = 4;</code>
       */
      public static final int MISSIONREWARD_VALUE = 4;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return CGPLAYERCHECKLOGIN;
          case 2: return GCPLAYERCHECKLOGIN;
          case 3: return MISSIONINFO;
          case 4: return MISSIONREWARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.common.msg.bean.BaseBean.BaseMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:bean.BaseMessage.Type)
    }

    private int bitField0_;
    // required .bean.BaseMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.common.msg.bean.BaseBean.BaseMessage.Type type_;
    /**
     * <code>required .bean.BaseMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .bean.BaseMessage.Type type = 1;</code>
     */
    public com.common.msg.bean.BaseBean.BaseMessage.Type getType() {
      return type_;
    }

    private void initFields() {
      type_ = com.common.msg.bean.BaseBean.BaseMessage.Type.CGPLAYERCHECKLOGIN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.common.msg.bean.BaseBean.BaseMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.common.msg.bean.BaseBean.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.BaseBean.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.common.msg.bean.BaseBean.BaseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.BaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.common.msg.bean.BaseBean.BaseMessage, Builder> implements com.common.msg.bean.BaseBean.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.msg.bean.BaseBean.internal_static_bean_BaseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.msg.bean.BaseBean.internal_static_bean_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.msg.bean.BaseBean.BaseMessage.class, com.common.msg.bean.BaseBean.BaseMessage.Builder.class);
      }

      // Construct using com.common.msg.bean.BaseBean.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.common.msg.bean.BaseBean.BaseMessage.Type.CGPLAYERCHECKLOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.msg.bean.BaseBean.internal_static_bean_BaseMessage_descriptor;
      }

      public com.common.msg.bean.BaseBean.BaseMessage getDefaultInstanceForType() {
        return com.common.msg.bean.BaseBean.BaseMessage.getDefaultInstance();
      }

      public com.common.msg.bean.BaseBean.BaseMessage build() {
        com.common.msg.bean.BaseBean.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.common.msg.bean.BaseBean.BaseMessage buildPartial() {
        com.common.msg.bean.BaseBean.BaseMessage result = new com.common.msg.bean.BaseBean.BaseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.msg.bean.BaseBean.BaseMessage) {
          return mergeFrom((com.common.msg.bean.BaseBean.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.msg.bean.BaseBean.BaseMessage other) {
        if (other == com.common.msg.bean.BaseBean.BaseMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.msg.bean.BaseBean.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.msg.bean.BaseBean.BaseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .bean.BaseMessage.Type type = 1;
      private com.common.msg.bean.BaseBean.BaseMessage.Type type_ = com.common.msg.bean.BaseBean.BaseMessage.Type.CGPLAYERCHECKLOGIN;
      /**
       * <code>required .bean.BaseMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .bean.BaseMessage.Type type = 1;</code>
       */
      public com.common.msg.bean.BaseBean.BaseMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .bean.BaseMessage.Type type = 1;</code>
       */
      public Builder setType(com.common.msg.bean.BaseBean.BaseMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .bean.BaseMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.common.msg.bean.BaseBean.BaseMessage.Type.CGPLAYERCHECKLOGIN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.BaseMessage)
    }

    static {
      defaultInstance = new BaseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bean.BaseMessage)
  }

  public static final int CGPLAYERCHECKLOGIN_FIELD_NUMBER = 100;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.bean.BaseBean.BaseMessage,
      com.common.msg.bean.PlayerBean.CGPlayerCheckLogin> cgPlayerCheckLogin = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.class,
        com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.getDefaultInstance());
  public static final int GCPLAYERCHECKLOGIN_FIELD_NUMBER = 101;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.bean.BaseBean.BaseMessage,
      com.common.msg.bean.PlayerBean.GCPlayerCheckLogin> gcPlayerCheckLogin = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.class,
        com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.getDefaultInstance());
  public static final int MISSIONINFO_FIELD_NUMBER = 200;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.bean.BaseBean.BaseMessage,
      com.common.msg.bean.MissionBean.MissionInfo> missionInfo = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.bean.MissionBean.MissionInfo.class,
        com.common.msg.bean.MissionBean.MissionInfo.getDefaultInstance());
  public static final int MISSIONREWARD_FIELD_NUMBER = 201;
  /**
   * <code>extend .bean.BaseMessage { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.common.msg.bean.BaseBean.BaseMessage,
      com.common.msg.bean.MissionBean.MissionReward> missionReward = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.common.msg.bean.MissionBean.MissionReward.class,
        com.common.msg.bean.MissionBean.MissionReward.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_BaseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bean_BaseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\004bean\032\rmission.proto\032\014pl" +
      "ayer.proto\"\231\001\n\013BaseMessage\022$\n\004type\030\001 \002(\016" +
      "2\026.bean.BaseMessage.Type\"Z\n\004Type\022\026\n\022CGPL" +
      "AYERCHECKLOGIN\020\001\022\026\n\022GCPLAYERCHECKLOGIN\020\002" +
      "\022\017\n\013MISSIONINFO\020\003\022\021\n\rMISSIONREWARD\020\004*\010\010d" +
      "\020\200\200\200\200\002:G\n\022cgPlayerCheckLogin\022\021.bean.Base" +
      "Message\030d \001(\0132\030.bean.CGPlayerCheckLogin:" +
      "G\n\022gcPlayerCheckLogin\022\021.bean.BaseMessage" +
      "\030e \001(\0132\030.bean.GCPlayerCheckLogin::\n\013miss" +
      "ionInfo\022\021.bean.BaseMessage\030\310\001 \001(\0132\021.bean",
      ".MissionInfo:>\n\rmissionReward\022\021.bean.Bas" +
      "eMessage\030\311\001 \001(\0132\023.bean.MissionRewardB\024\n\010" +
      "com.beanB\010BaseBean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bean_BaseMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bean_BaseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bean_BaseMessage_descriptor,
              new java.lang.String[] { "Type", });
          cgPlayerCheckLogin.internalInit(descriptor.getExtensions().get(0));
          gcPlayerCheckLogin.internalInit(descriptor.getExtensions().get(1));
          missionInfo.internalInit(descriptor.getExtensions().get(2));
          missionReward.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.common.msg.bean.MissionBean.getDescriptor(),
          com.common.msg.bean.PlayerBean.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
