// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mission.proto

package com.common.msg.bean;

public final class MissionBean {
  private MissionBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MissionInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 missionId = 1;
    /**
     * <code>required int32 missionId = 1;</code>
     */
    boolean hasMissionId();
    /**
     * <code>required int32 missionId = 1;</code>
     */
    int getMissionId();

    // optional int32 star = 2 [default = 0];
    /**
     * <code>optional int32 star = 2 [default = 0];</code>
     */
    boolean hasStar();
    /**
     * <code>optional int32 star = 2 [default = 0];</code>
     */
    int getStar();

    // optional int32 selfRecord = 3 [default = 0];
    /**
     * <code>optional int32 selfRecord = 3 [default = 0];</code>
     */
    boolean hasSelfRecord();
    /**
     * <code>optional int32 selfRecord = 3 [default = 0];</code>
     */
    int getSelfRecord();
  }
  /**
   * Protobuf type {@code bean.MissionInfo}
   */
  public static final class MissionInfo extends
      com.google.protobuf.GeneratedMessage
      implements MissionInfoOrBuilder {
    // Use MissionInfo.newBuilder() to construct.
    private MissionInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MissionInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MissionInfo defaultInstance;
    public static MissionInfo getDefaultInstance() {
      return defaultInstance;
    }

    public MissionInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MissionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              missionId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              star_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              selfRecord_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.msg.bean.MissionBean.internal_static_bean_MissionInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.msg.bean.MissionBean.internal_static_bean_MissionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.msg.bean.MissionBean.MissionInfo.class, com.common.msg.bean.MissionBean.MissionInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<MissionInfo> PARSER =
        new com.google.protobuf.AbstractParser<MissionInfo>() {
      public MissionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MissionInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MissionInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 missionId = 1;
    public static final int MISSIONID_FIELD_NUMBER = 1;
    private int missionId_;
    /**
     * <code>required int32 missionId = 1;</code>
     */
    public boolean hasMissionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 missionId = 1;</code>
     */
    public int getMissionId() {
      return missionId_;
    }

    // optional int32 star = 2 [default = 0];
    public static final int STAR_FIELD_NUMBER = 2;
    private int star_;
    /**
     * <code>optional int32 star = 2 [default = 0];</code>
     */
    public boolean hasStar() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 star = 2 [default = 0];</code>
     */
    public int getStar() {
      return star_;
    }

    // optional int32 selfRecord = 3 [default = 0];
    public static final int SELFRECORD_FIELD_NUMBER = 3;
    private int selfRecord_;
    /**
     * <code>optional int32 selfRecord = 3 [default = 0];</code>
     */
    public boolean hasSelfRecord() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 selfRecord = 3 [default = 0];</code>
     */
    public int getSelfRecord() {
      return selfRecord_;
    }

    private void initFields() {
      missionId_ = 0;
      star_ = 0;
      selfRecord_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMissionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, missionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, star_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, selfRecord_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, missionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, star_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, selfRecord_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.common.msg.bean.MissionBean.MissionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.MissionBean.MissionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.common.msg.bean.MissionBean.MissionInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.MissionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.common.msg.bean.MissionBean.MissionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.msg.bean.MissionBean.internal_static_bean_MissionInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.msg.bean.MissionBean.internal_static_bean_MissionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.msg.bean.MissionBean.MissionInfo.class, com.common.msg.bean.MissionBean.MissionInfo.Builder.class);
      }

      // Construct using com.bean.MissionBean.MissionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        missionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        star_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        selfRecord_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.msg.bean.MissionBean.internal_static_bean_MissionInfo_descriptor;
      }

      public com.common.msg.bean.MissionBean.MissionInfo getDefaultInstanceForType() {
        return com.common.msg.bean.MissionBean.MissionInfo.getDefaultInstance();
      }

      public com.common.msg.bean.MissionBean.MissionInfo build() {
        com.common.msg.bean.MissionBean.MissionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.common.msg.bean.MissionBean.MissionInfo buildPartial() {
        com.common.msg.bean.MissionBean.MissionInfo result = new com.common.msg.bean.MissionBean.MissionInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.missionId_ = missionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.star_ = star_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.selfRecord_ = selfRecord_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.msg.bean.MissionBean.MissionInfo) {
          return mergeFrom((com.common.msg.bean.MissionBean.MissionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.msg.bean.MissionBean.MissionInfo other) {
        if (other == com.common.msg.bean.MissionBean.MissionInfo.getDefaultInstance()) return this;
        if (other.hasMissionId()) {
          setMissionId(other.getMissionId());
        }
        if (other.hasStar()) {
          setStar(other.getStar());
        }
        if (other.hasSelfRecord()) {
          setSelfRecord(other.getSelfRecord());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMissionId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.msg.bean.MissionBean.MissionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.msg.bean.MissionBean.MissionInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 missionId = 1;
      private int missionId_ ;
      /**
       * <code>required int32 missionId = 1;</code>
       */
      public boolean hasMissionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 missionId = 1;</code>
       */
      public int getMissionId() {
        return missionId_;
      }
      /**
       * <code>required int32 missionId = 1;</code>
       */
      public Builder setMissionId(int value) {
        bitField0_ |= 0x00000001;
        missionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 missionId = 1;</code>
       */
      public Builder clearMissionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        missionId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 star = 2 [default = 0];
      private int star_ ;
      /**
       * <code>optional int32 star = 2 [default = 0];</code>
       */
      public boolean hasStar() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 star = 2 [default = 0];</code>
       */
      public int getStar() {
        return star_;
      }
      /**
       * <code>optional int32 star = 2 [default = 0];</code>
       */
      public Builder setStar(int value) {
        bitField0_ |= 0x00000002;
        star_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 star = 2 [default = 0];</code>
       */
      public Builder clearStar() {
        bitField0_ = (bitField0_ & ~0x00000002);
        star_ = 0;
        onChanged();
        return this;
      }

      // optional int32 selfRecord = 3 [default = 0];
      private int selfRecord_ ;
      /**
       * <code>optional int32 selfRecord = 3 [default = 0];</code>
       */
      public boolean hasSelfRecord() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 selfRecord = 3 [default = 0];</code>
       */
      public int getSelfRecord() {
        return selfRecord_;
      }
      /**
       * <code>optional int32 selfRecord = 3 [default = 0];</code>
       */
      public Builder setSelfRecord(int value) {
        bitField0_ |= 0x00000004;
        selfRecord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 selfRecord = 3 [default = 0];</code>
       */
      public Builder clearSelfRecord() {
        bitField0_ = (bitField0_ & ~0x00000004);
        selfRecord_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.MissionInfo)
    }

    static {
      defaultInstance = new MissionInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bean.MissionInfo)
  }

  public interface MissionRewardOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 missionRewardId = 1;
    /**
     * <code>required int32 missionRewardId = 1;</code>
     */
    boolean hasMissionRewardId();
    /**
     * <code>required int32 missionRewardId = 1;</code>
     */
    int getMissionRewardId();

    // optional int32 ifFetch = 2 [default = 0];
    /**
     * <code>optional int32 ifFetch = 2 [default = 0];</code>
     */
    boolean hasIfFetch();
    /**
     * <code>optional int32 ifFetch = 2 [default = 0];</code>
     */
    int getIfFetch();
  }
  /**
   * Protobuf type {@code bean.MissionReward}
   */
  public static final class MissionReward extends
      com.google.protobuf.GeneratedMessage
      implements MissionRewardOrBuilder {
    // Use MissionReward.newBuilder() to construct.
    private MissionReward(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MissionReward(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MissionReward defaultInstance;
    public static MissionReward getDefaultInstance() {
      return defaultInstance;
    }

    public MissionReward getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MissionReward(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              missionRewardId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ifFetch_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.msg.bean.MissionBean.internal_static_bean_MissionReward_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.msg.bean.MissionBean.internal_static_bean_MissionReward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.msg.bean.MissionBean.MissionReward.class, com.common.msg.bean.MissionBean.MissionReward.Builder.class);
    }

    public static com.google.protobuf.Parser<MissionReward> PARSER =
        new com.google.protobuf.AbstractParser<MissionReward>() {
      public MissionReward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MissionReward(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MissionReward> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 missionRewardId = 1;
    public static final int MISSIONREWARDID_FIELD_NUMBER = 1;
    private int missionRewardId_;
    /**
     * <code>required int32 missionRewardId = 1;</code>
     */
    public boolean hasMissionRewardId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 missionRewardId = 1;</code>
     */
    public int getMissionRewardId() {
      return missionRewardId_;
    }

    // optional int32 ifFetch = 2 [default = 0];
    public static final int IFFETCH_FIELD_NUMBER = 2;
    private int ifFetch_;
    /**
     * <code>optional int32 ifFetch = 2 [default = 0];</code>
     */
    public boolean hasIfFetch() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 ifFetch = 2 [default = 0];</code>
     */
    public int getIfFetch() {
      return ifFetch_;
    }

    private void initFields() {
      missionRewardId_ = 0;
      ifFetch_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMissionRewardId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, missionRewardId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ifFetch_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, missionRewardId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ifFetch_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.common.msg.bean.MissionBean.MissionReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.MissionBean.MissionReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.common.msg.bean.MissionBean.MissionReward prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.MissionReward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.common.msg.bean.MissionBean.MissionRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.msg.bean.MissionBean.internal_static_bean_MissionReward_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.msg.bean.MissionBean.internal_static_bean_MissionReward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.msg.bean.MissionBean.MissionReward.class, com.common.msg.bean.MissionBean.MissionReward.Builder.class);
      }

      // Construct using com.bean.MissionBean.MissionReward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        missionRewardId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ifFetch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.msg.bean.MissionBean.internal_static_bean_MissionReward_descriptor;
      }

      public com.common.msg.bean.MissionBean.MissionReward getDefaultInstanceForType() {
        return com.common.msg.bean.MissionBean.MissionReward.getDefaultInstance();
      }

      public com.common.msg.bean.MissionBean.MissionReward build() {
        com.common.msg.bean.MissionBean.MissionReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.common.msg.bean.MissionBean.MissionReward buildPartial() {
        com.common.msg.bean.MissionBean.MissionReward result = new com.common.msg.bean.MissionBean.MissionReward(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.missionRewardId_ = missionRewardId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ifFetch_ = ifFetch_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.msg.bean.MissionBean.MissionReward) {
          return mergeFrom((com.common.msg.bean.MissionBean.MissionReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.msg.bean.MissionBean.MissionReward other) {
        if (other == com.common.msg.bean.MissionBean.MissionReward.getDefaultInstance()) return this;
        if (other.hasMissionRewardId()) {
          setMissionRewardId(other.getMissionRewardId());
        }
        if (other.hasIfFetch()) {
          setIfFetch(other.getIfFetch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMissionRewardId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.msg.bean.MissionBean.MissionReward parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.msg.bean.MissionBean.MissionReward) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 missionRewardId = 1;
      private int missionRewardId_ ;
      /**
       * <code>required int32 missionRewardId = 1;</code>
       */
      public boolean hasMissionRewardId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 missionRewardId = 1;</code>
       */
      public int getMissionRewardId() {
        return missionRewardId_;
      }
      /**
       * <code>required int32 missionRewardId = 1;</code>
       */
      public Builder setMissionRewardId(int value) {
        bitField0_ |= 0x00000001;
        missionRewardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 missionRewardId = 1;</code>
       */
      public Builder clearMissionRewardId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        missionRewardId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 ifFetch = 2 [default = 0];
      private int ifFetch_ ;
      /**
       * <code>optional int32 ifFetch = 2 [default = 0];</code>
       */
      public boolean hasIfFetch() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 ifFetch = 2 [default = 0];</code>
       */
      public int getIfFetch() {
        return ifFetch_;
      }
      /**
       * <code>optional int32 ifFetch = 2 [default = 0];</code>
       */
      public Builder setIfFetch(int value) {
        bitField0_ |= 0x00000002;
        ifFetch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ifFetch = 2 [default = 0];</code>
       */
      public Builder clearIfFetch() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ifFetch_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.MissionReward)
    }

    static {
      defaultInstance = new MissionReward(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bean.MissionReward)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_MissionInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bean_MissionInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_MissionReward_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bean_MissionReward_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmission.proto\022\004bean\"H\n\013MissionInfo\022\021\n\t" +
      "missionId\030\001 \002(\005\022\017\n\004star\030\002 \001(\005:\0010\022\025\n\nself" +
      "Record\030\003 \001(\005:\0010\"<\n\rMissionReward\022\027\n\017miss" +
      "ionRewardId\030\001 \002(\005\022\022\n\007ifFetch\030\002 \001(\005:\0010B\027\n" +
      "\010com.beanB\013MissionBean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bean_MissionInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bean_MissionInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bean_MissionInfo_descriptor,
              new java.lang.String[] { "MissionId", "Star", "SelfRecord", });
          internal_static_bean_MissionReward_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_bean_MissionReward_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bean_MissionReward_descriptor,
              new java.lang.String[] { "MissionRewardId", "IfFetch", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
