// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package com.common.msg.bean;

public final class PlayerBean {
  private PlayerBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CGPlayerCheckLoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 playerId = 1;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int32 playerId = 1;</code>
     */
    int getPlayerId();

    // optional string userCode = 2 [default = ""];
    /**
     * <code>optional string userCode = 2 [default = ""];</code>
     */
    boolean hasUserCode();
    /**
     * <code>optional string userCode = 2 [default = ""];</code>
     */
    java.lang.String getUserCode();
    /**
     * <code>optional string userCode = 2 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getUserCodeBytes();

    // optional string deviceID = 3 [default = ""];
    /**
     * <code>optional string deviceID = 3 [default = ""];</code>
     */
    boolean hasDeviceID();
    /**
     * <code>optional string deviceID = 3 [default = ""];</code>
     */
    java.lang.String getDeviceID();
    /**
     * <code>optional string deviceID = 3 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getDeviceIDBytes();
  }
  /**
   * Protobuf type {@code bean.CGPlayerCheckLogin}
   */
  public static final class CGPlayerCheckLogin extends
      com.google.protobuf.GeneratedMessage
      implements CGPlayerCheckLoginOrBuilder {
    // Use CGPlayerCheckLogin.newBuilder() to construct.
    private CGPlayerCheckLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CGPlayerCheckLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CGPlayerCheckLogin defaultInstance;
    public static CGPlayerCheckLogin getDefaultInstance() {
      return defaultInstance;
    }

    public CGPlayerCheckLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CGPlayerCheckLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userCode_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              deviceID_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.msg.bean.PlayerBean.internal_static_bean_CGPlayerCheckLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.msg.bean.PlayerBean.internal_static_bean_CGPlayerCheckLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.class, com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<CGPlayerCheckLogin> PARSER =
        new com.google.protobuf.AbstractParser<CGPlayerCheckLogin>() {
      public CGPlayerCheckLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CGPlayerCheckLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CGPlayerCheckLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    // optional string userCode = 2 [default = ""];
    public static final int USERCODE_FIELD_NUMBER = 2;
    private java.lang.Object userCode_;
    /**
     * <code>optional string userCode = 2 [default = ""];</code>
     */
    public boolean hasUserCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string userCode = 2 [default = ""];</code>
     */
    public java.lang.String getUserCode() {
      java.lang.Object ref = userCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userCode = 2 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getUserCodeBytes() {
      java.lang.Object ref = userCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string deviceID = 3 [default = ""];
    public static final int DEVICEID_FIELD_NUMBER = 3;
    private java.lang.Object deviceID_;
    /**
     * <code>optional string deviceID = 3 [default = ""];</code>
     */
    public boolean hasDeviceID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string deviceID = 3 [default = ""];</code>
     */
    public java.lang.String getDeviceID() {
      java.lang.Object ref = deviceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceID = 3 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIDBytes() {
      java.lang.Object ref = deviceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      playerId_ = 0;
      userCode_ = "";
      deviceID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDeviceIDBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDeviceIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.common.msg.bean.PlayerBean.CGPlayerCheckLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.CGPlayerCheckLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.common.msg.bean.PlayerBean.CGPlayerCheckLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.msg.bean.PlayerBean.internal_static_bean_CGPlayerCheckLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.msg.bean.PlayerBean.internal_static_bean_CGPlayerCheckLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.class, com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.Builder.class);
      }

      // Construct using com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.msg.bean.PlayerBean.internal_static_bean_CGPlayerCheckLogin_descriptor;
      }

      public com.common.msg.bean.PlayerBean.CGPlayerCheckLogin getDefaultInstanceForType() {
        return com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.getDefaultInstance();
      }

      public com.common.msg.bean.PlayerBean.CGPlayerCheckLogin build() {
        com.common.msg.bean.PlayerBean.CGPlayerCheckLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.common.msg.bean.PlayerBean.CGPlayerCheckLogin buildPartial() {
        com.common.msg.bean.PlayerBean.CGPlayerCheckLogin result = new com.common.msg.bean.PlayerBean.CGPlayerCheckLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userCode_ = userCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceID_ = deviceID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.msg.bean.PlayerBean.CGPlayerCheckLogin) {
          return mergeFrom((com.common.msg.bean.PlayerBean.CGPlayerCheckLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.msg.bean.PlayerBean.CGPlayerCheckLogin other) {
        if (other == com.common.msg.bean.PlayerBean.CGPlayerCheckLogin.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasUserCode()) {
          bitField0_ |= 0x00000002;
          userCode_ = other.userCode_;
          onChanged();
        }
        if (other.hasDeviceID()) {
          bitField0_ |= 0x00000004;
          deviceID_ = other.deviceID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.msg.bean.PlayerBean.CGPlayerCheckLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.msg.bean.PlayerBean.CGPlayerCheckLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 playerId = 1;
      private int playerId_ ;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // optional string userCode = 2 [default = ""];
      private java.lang.Object userCode_ = "";
      /**
       * <code>optional string userCode = 2 [default = ""];</code>
       */
      public boolean hasUserCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string userCode = 2 [default = ""];</code>
       */
      public java.lang.String getUserCode() {
        java.lang.Object ref = userCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userCode = 2 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getUserCodeBytes() {
        java.lang.Object ref = userCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userCode = 2 [default = ""];</code>
       */
      public Builder setUserCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userCode = 2 [default = ""];</code>
       */
      public Builder clearUserCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userCode_ = getDefaultInstance().getUserCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userCode = 2 [default = ""];</code>
       */
      public Builder setUserCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userCode_ = value;
        onChanged();
        return this;
      }

      // optional string deviceID = 3 [default = ""];
      private java.lang.Object deviceID_ = "";
      /**
       * <code>optional string deviceID = 3 [default = ""];</code>
       */
      public boolean hasDeviceID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string deviceID = 3 [default = ""];</code>
       */
      public java.lang.String getDeviceID() {
        java.lang.Object ref = deviceID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceID = 3 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIDBytes() {
        java.lang.Object ref = deviceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceID = 3 [default = ""];</code>
       */
      public Builder setDeviceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceID = 3 [default = ""];</code>
       */
      public Builder clearDeviceID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceID_ = getDefaultInstance().getDeviceID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceID = 3 [default = ""];</code>
       */
      public Builder setDeviceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceID_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.CGPlayerCheckLogin)
    }

    static {
      defaultInstance = new CGPlayerCheckLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bean.CGPlayerCheckLogin)
  }

  public interface GCPlayerCheckLoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 playerId = 1;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int32 playerId = 1;</code>
     */
    int getPlayerId();
  }
  /**
   * Protobuf type {@code bean.GCPlayerCheckLogin}
   */
  public static final class GCPlayerCheckLogin extends
      com.google.protobuf.GeneratedMessage
      implements GCPlayerCheckLoginOrBuilder {
    // Use GCPlayerCheckLogin.newBuilder() to construct.
    private GCPlayerCheckLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GCPlayerCheckLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GCPlayerCheckLogin defaultInstance;
    public static GCPlayerCheckLogin getDefaultInstance() {
      return defaultInstance;
    }

    public GCPlayerCheckLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GCPlayerCheckLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.msg.bean.PlayerBean.internal_static_bean_GCPlayerCheckLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.msg.bean.PlayerBean.internal_static_bean_GCPlayerCheckLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.class, com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<GCPlayerCheckLogin> PARSER =
        new com.google.protobuf.AbstractParser<GCPlayerCheckLogin>() {
      public GCPlayerCheckLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GCPlayerCheckLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GCPlayerCheckLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    private void initFields() {
      playerId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.common.msg.bean.PlayerBean.GCPlayerCheckLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.GCPlayerCheckLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.common.msg.bean.PlayerBean.GCPlayerCheckLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.msg.bean.PlayerBean.internal_static_bean_GCPlayerCheckLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.msg.bean.PlayerBean.internal_static_bean_GCPlayerCheckLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.class, com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.Builder.class);
      }

      // Construct using com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.msg.bean.PlayerBean.internal_static_bean_GCPlayerCheckLogin_descriptor;
      }

      public com.common.msg.bean.PlayerBean.GCPlayerCheckLogin getDefaultInstanceForType() {
        return com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.getDefaultInstance();
      }

      public com.common.msg.bean.PlayerBean.GCPlayerCheckLogin build() {
        com.common.msg.bean.PlayerBean.GCPlayerCheckLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.common.msg.bean.PlayerBean.GCPlayerCheckLogin buildPartial() {
        com.common.msg.bean.PlayerBean.GCPlayerCheckLogin result = new com.common.msg.bean.PlayerBean.GCPlayerCheckLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.msg.bean.PlayerBean.GCPlayerCheckLogin) {
          return mergeFrom((com.common.msg.bean.PlayerBean.GCPlayerCheckLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.msg.bean.PlayerBean.GCPlayerCheckLogin other) {
        if (other == com.common.msg.bean.PlayerBean.GCPlayerCheckLogin.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.msg.bean.PlayerBean.GCPlayerCheckLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.msg.bean.PlayerBean.GCPlayerCheckLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 playerId = 1;
      private int playerId_ ;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bean.GCPlayerCheckLogin)
    }

    static {
      defaultInstance = new GCPlayerCheckLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bean.GCPlayerCheckLogin)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_CGPlayerCheckLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bean_CGPlayerCheckLogin_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_GCPlayerCheckLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bean_GCPlayerCheckLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014player.proto\022\004bean\"N\n\022CGPlayerCheckLog" +
      "in\022\020\n\010playerId\030\001 \002(\005\022\022\n\010userCode\030\002 \001(\t:\000" +
      "\022\022\n\010deviceID\030\003 \001(\t:\000\"&\n\022GCPlayerCheckLog" +
      "in\022\020\n\010playerId\030\001 \002(\005B\026\n\010com.beanB\nPlayer" +
      "Bean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bean_CGPlayerCheckLogin_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bean_CGPlayerCheckLogin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bean_CGPlayerCheckLogin_descriptor,
              new java.lang.String[] { "PlayerId", "UserCode", "DeviceID", });
          internal_static_bean_GCPlayerCheckLogin_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_bean_GCPlayerCheckLogin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bean_GCPlayerCheckLogin_descriptor,
              new java.lang.String[] { "PlayerId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
